name: bobrossquotes 
adopt-info: bobrossquotes
summary: A collection of Bob Ross quotes 
description: |
  Get inspiration and a happier view on life from Bob Ross...in your terminal.

license: MIT
base: core24
grade: stable 
confinement: strict
source-code: https://github.com/kz6fittycent/BobRossQuotes
issues: https://github.com/kz6fittycent/BobRossQuotes/issues

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  ppc64el:
    build-on: [ppc64el]
    build-for: [ppc64el]
  s390x:
    build-on: [s390x]
    build-for: [s390x]

apps:
  bobrossquotes:
    command: bin/bobross
    environment:
      LC_ALL: C.UTF-8
     
parts: 
  bobrossquotes:
    source: https://github.com/kz6fittycent/BobRossQuotes
    source-type: git
    plugin: python
    
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
