name: bobrossquotes 
adopt-info: bobrossquotes
summary: A collection of Bob Ross quotes 
description: |
  Get inspiration and a happier view on life from Bob Ross...in your terminal.

license: MIT
base: core24
grade: stable 
confinement: strict

apps:
  bobrossquotes:
    command: bin/bobross
    environment:
      LC_ALL: C.UTF-8
     
parts: 
  bobrossquotes:
    source: https://github.com/kz6fittycent/BobRossQuotes
    source-type: git
    plugin: python
    
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
