name: bobrossquotes 
adopt-info: bobrossquotes
summary: A collection of Bob Ross quotes 
description: |
  Get inspiration and a happier view on life from Bob Ross...in your terminal.

license: MIT

base: core18
grade: stable 
confinement: strict

apps:
  bobrossquotes:
    command: bobross
    environment:
      LC_ALL: C.UTF-8
     
parts: 
  bobrossquotes:
    source: https://github.com/kz6fittycent/BobRossQuotes
    source-type: git
    plugin: python
    python-version: python3
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"    
    
    build-packages:
      - python3
      
    stage-packages:
      - python3
